name: MFP Daily Run

on:
  schedule:
    - cron:  '12 3 * * *'
  workflow_dispatch:
    inputs:
          days-back:
            description: 'Number of days back to go'
            required: false
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.x
    - name: Install MFP
      run: dotnet tool install --global mfp --version 0.2.3
    - shell: bash
      env:
        DAYS_BACK_DEFAULT: 5
        MFP_PASSWORD: ${{ secrets.MFP_PASSWORD }}
        MFP_USERNAME: ${{ secrets.MFP_USERNAME }}
      run: |
        echo "${{ github.event.inputs.days-back || env.DAYS_BACK_DEFAULT }}" |
        mfp export --num-days=5 --format=csv --username="$MFP_USERNAME" --password="$MFP_PASSWORD"
        
