name: MFP Daily Run

on:
  schedule:
    - cron:  '12 3 * * *'
  workflow_dispatch:
    inputs:
      days-back:
        description: 'Number of days back to go'
        required: false
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.x
    - name: Install MFP
      run: dotnet tool install --global mfp --version 0.2.4
    - shell: bash
      env:
        DAYS_BACK_DEFAULT: 5
        MFP_PASSWORD: ${{ secrets.MFP_PASSWORD }}
        MFP_USERNAME: ${{ secrets.MFP_USERNAME }}
      run: |
        mfp export --num-days="${{ github.event.inputs.days-back || env.DAYS_BACK_DEFAULT }}" --format=csv --username="$MFP_USERNAME" --password="$MFP_PASSWORD" > mfp-${{steps.date.outputs.date}}.csv
    - name: upload to azure
      uses: bacongobbler/azure-blob-storage-upload@v1.2.0
      with:
        source_dir: .
        container_name: mfp
        connection_string: ${{ secrets.AZURE_BLOB_STORAGE_CONNECTION_STRING }}
        extra_args: '--pattern *.csv'
        sync: false

