name: MFP Daily Run

on:
  schedule:
    - cron:  '12 3 * * *'
  workflow_dispatch:
    inputs:
          days-back:
            description: 'Number of days back to go'
            required: true
            default: 1
jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.x
    - name: Install MFP
      run: dotnet tool install --global mfp --version 0.2.2
    - name: Build
      run: mfp export --num-days=5 --format=csv --username=${{ secrets.MFP_USERNAME }} --password=${{ secrets.MFP_PASSWORD }} --verbosity=Trace
  
