name: MyFitnessPal.Data

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  create:

jobs:
  build:
    name: Build Core
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build MyFitnessPal.Data/MyFitnessPal.Data.csproj

    - name: Pack
      run: dotnet pack MyFitnessPal.Data/MyFitnessPal.Data.csproj --configuration=Release

    - uses: actions/upload-artifact@v2
      with:
        name: nupkg
        path: MyFitnessPal.Data/nupkg/**/*.nupkg
